apiVersion: apps/v1
kind: Deployment
metadata:
  name: es01-deployment
  namespace: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es01
  template:
    metadata:
      labels:
        app: es01
    spec:
      containers:
        - name: es01
          image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          env:
            - name: node.name
              value: "es01"
            - name: discovery.seed_hosts
              value: "es02"
            - name: cluster.initial_master_nodes
              value: "es01,es02"
            - name: cluster.name
              value: "docker-cluster"
            - name: bootstrap.memory_lock
              value: "true"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: es01-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es01-data
          emptyDir: {}

